### ISSUE TITLE
does not build with haskell-src-exts 1.18+

### ISSUE THREAD

**Issue by juhp** [gelisam/hawk#168]
Hawk does not seem to build with haskell-src-exts >= 1.18.
It would be nice to fix this or add an upper bound on haskell-src-exts in Hackage.

It might be nice to add Hawk to Stackage too. :)

**Comment by juhp** [comment]
```
    [ 6 of 29] Compiling Language.Haskell.Exts.Location ( src/Language/Haskell/Exts/Location.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/hawk/hawk-tmp/Language/Haskell/Exts/Location.o )
    
    /home/petersen/tmp/stack19486/haskell-awk-1.1.1/src/Language/Haskell/Exts/Location.hs:14:26: error:
        Not in scope: type constructor or class ‘SrcLoc’
    
    /home/petersen/tmp/stack19486/haskell-awk-1.1.1/src/Language/Haskell/Exts/Location.hs:16:19: error:
        Not in scope: type constructor or class ‘SrcLoc’
    
    /home/petersen/tmp/stack19486/haskell-awk-1.1.1/src/Language/Haskell/Exts/Location.hs:75:38: error:
        Not in scope: type constructor or class ‘SrcLoc’
    
    /home/petersen/tmp/stack19486/haskell-awk-1.1.1/src/Language/Haskell/Exts/Location.hs:82:38: error:
        Not in scope: type constructor or class ‘SrcLoc’
```

**Comment by gelisam** [comment]
Fixed by #191, which bumped to a newer haskell-src-exts. I have also added an upper-bound on hackage for the already-released versions; sorry it took me two years to do so, I was certain I already did that, and it's only now that I double-checked before closing this issue that I finally realized I hadn't!
