### ISSUE TITLE
fix upper-bounds

### ISSUE THREAD

**Issue by gelisam** [gelisam/hawk#224]
When I tried `cabal new-build` with ghc-8.8.1, I got a compilation error rather than a "no build plan error".

Let's fix this on released versions as well, via revisions.

**Comment by gelisam** [comment]
Added `network < 2.7.0.0` revisions to all published versions.

**Comment by gelisam** [comment]
On `master`, `cabal new-build` successfully builds with ghc-8.0.2, but not ghc-8.6.5. MonadFail issues. When did that get introduced? [The docs](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Monad-Fail.html) say base-4.9.0.0, but that's ghc-8.0.1, so that's clearly not right or ghc-8.0.2 would fail too. I guess what I want to know is not when the MonadFail typeclass became available, but when it became mandatory?

**Comment by gelisam** [comment]
Hmm, `fail` is [still in `Monad` today](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Monad.html#t:Monad), actually, so it's still not mandatory. I guess I'm using a dependency which upgraded to MonadFail, so I need to find that dependency and put an upper-bound on it (and eventually upgrade to MonadFail myself).

* ghc-8.0.2: pass
* ghc-
* ghc-8.6.5: MonadFail issues

**Comment by gelisam** [comment]
Taking a closer look at the error message, it says "Could not deduce (Control.Monad.Fail.MonadFail m) arising from a do statement with the failable pattern ‘Just s’`. So it really is ghc, not one of my dependencies.

**Comment by gelisam** [comment]
* ghc-8.0.2: pass
* ghc-8.4.4: pass
* ghc-8.6.5: MonadFail issues

**Comment by gelisam** [comment]
It's in [the ghc-8.6.1 release notes](https://downloads.haskell.org/~ghc/8.6.1/docs/html/users_guide/8.6.1-notes.html): "MonadFailDesugaring is now enabled by default". So I need to add the `ghc < 8.6` upper bound.
